// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.summation.tars.proxy.multiply;

import cn.nju.summation.tars.summation.Response;
import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class MultiplyResourcePrxCallback extends TarsAbstractCallback {

	public abstract void callback_doMultiply(Response ret, MultiplyData dataOut);

}
