// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.myproxy.tars.prime;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface PrimeResourcePrx {

	public Response isPrime(@TarsHolder Holder<PrimeData> dataOut);

	public Response isPrime(@TarsHolder Holder<PrimeData> dataOut, @TarsContext java.util.Map<String, String> ctx);

	public void async_isPrime(@TarsCallback PrimeResourcePrxCallback callback);

	public void async_isPrime(@TarsCallback PrimeResourcePrxCallback callback, @TarsContext java.util.Map<String, String> ctx);
}
