// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.myproxy.tars.prime;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class PrimeResourcePrxCallback extends TarsAbstractCallback {

	public abstract void callback_isPrime(Response ret, PrimeData dataOut);

}
