// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.summation.test.tars.summation;

import cn.nju.summation.tars.summation.Response;
import cn.nju.summation.tars.summation.SummationData;
import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class SummationResourcePrxCallback extends TarsAbstractCallback {

	public abstract void callback_doSummation(Response ret, SummationData dataOut);

}
