// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.summation.test.tars.summation;

import cn.nju.summation.tars.summation.Response;
import cn.nju.summation.tars.summation.SummationData;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface SummationResourcePrx {

	public Response doSummation(@TarsHolder Holder<SummationData> dataOut);

	public Response doSummation(@TarsHolder Holder<SummationData> dataOut, @TarsContext java.util.Map<String, String> ctx);

	public void async_doSummation(@TarsCallback SummationResourcePrxCallback callback);

	public void async_doSummation(@TarsCallback SummationResourcePrxCallback callback, @TarsContext java.util.Map<String, String> ctx);
}
