// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.multiplication.test.tars.multiply;

import cn.nju.multiplication.tars.multiply.MultiplyData;
import cn.nju.multiplication.tars.multiply.Response;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface MultiplyResourcePrx {

	public Response doMultiply(@TarsHolder Holder<MultiplyData> dataOut);

	public Response doMultiply(@TarsHolder Holder<MultiplyData> dataOut, @TarsContext java.util.Map<String, String> ctx);

	public void async_doMultiply(@TarsCallback MultiplyResourcePrxCallback callback);

	public void async_doMultiply(@TarsCallback MultiplyResourcePrxCallback callback, @TarsContext java.util.Map<String, String> ctx);
}
