// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.prime.tars.proxy.summation;

import cn.nju.prime.tars.prime.Response;
import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class SummationResourcePrxCallback extends TarsAbstractCallback {

	public abstract void callback_doSummation(Response ret, SummationData dataOut);

}
