// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.random.test.tars.random;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface RandomResourcePrx {

	public Response getRandomData(@TarsHolder Holder<RandomData> dataOut);

	public Response getRandomData(@TarsHolder Holder<RandomData> dataOut, @TarsContext java.util.Map<String, String> ctx);

	public void async_getRandomData(@TarsCallback RandomResourcePrxCallback callback);

	public void async_getRandomData(@TarsCallback RandomResourcePrxCallback callback, @TarsContext java.util.Map<String, String> ctx);
}
