// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.tarstestclient.tars.test;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class TestPrxCallback extends TarsAbstractCallback {

	public abstract void callback_testString(String ret);

	public abstract void callback_testB2S(String ret);

	public abstract void callback_testS2B(String ret);

}
