// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package cn.nju.prime.test.tars.prime;

import cn.nju.prime.tars.prime.PrimeData;
import cn.nju.prime.tars.prime.Response;
import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class PrimeResourcePrxCallback extends TarsAbstractCallback {

	public abstract void callback_isPrime(Response ret, PrimeData dataOut);

}
